# Generated by Django 6.0.6 on 2026-07-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first on the store page')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('specification', models.CharField(blank=True, help_text="e.g. '3S Li-ion, up to 2A' or '18V, 10-20W mono/poly'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.PositiveIntegerField(help_text='Estimated low price in INR')),
                ('price_max', models.PositiveIntegerField(help_text='Estimated high price in INR')),
                ('affiliate_url', models.URLField(blank=True, help_text='Amazon / Robu.in / etc link. Leave blank if not sourced yet.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text="Optional: why you personally use this one. Shown on the product card. This is what keeps 'Tools' feeling curated instead of generic.", max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, help_text="e.g. 'critical — see wiring notes' or 'optional'", max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
            options={
                'ordering': ['product__category__order', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short line shown on the store landing page', max_length=200)),
                ('summary', models.TextField(help_text='2-3 sentence overview for the store listing')),
                ('full_description', models.TextField(blank=True, help_text='Longer write-up: how it works, wiring notes, safety notes, etc.')),
                ('blog_post_url', models.URLField(blank=True, help_text='Link to the matching blog write-up, if any')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store/kits/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/embed link — add when ready')),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden)'), ('coming_soon', 'Coming soon'), ('preorder', 'Open for preorder'), ('live', 'Available now')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(related_name='kits', through='store.KitComponent', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreorderInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, help_text="Tick once you've followed up")),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='store.projectkit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kitcomponent',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.projectkit'),
        ),
        migrations.AlterUniqueTogether(
            name='kitcomponent',
            unique_together={('kit', 'product')},
        ),
    ]
