# Generated by Django 4.2.7 on 2026-08-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkit',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO summary, 150-160 characters. Leave blank to auto-generate from summary.', max_length=160),
        ),
    ]
