# Generated by Django 4.2.7 on 2026-07-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_post_is_hidden'),
        ('blog', '0002_post_is_hidden'),
    ]

    operations = [
    ]
