# Generated by Django 4.2.7 on 2026-08-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_post_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO summary, 150-160 characters. Leave blank to auto-generate from content.', max_length=160),
        ),
    ]
