# Generated by Django 6.0.6 on 2026-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='air_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
