# Generated by Django 4.2.7 on 2026-07-08 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label, not shown to visitors",
                        max_length=150,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        help_text="Comma-separated. Include how people actually phrase it, not just the product name — e.g. 'pump not working, pump silent, no water'"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        help_text="The canned answer shown to the visitor"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority wins on a tied keyword score",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products to surface (with Buy links) alongside this answer",
                        related_name="intents",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChatQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("matched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="assistant.intent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chat queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
